AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'

Rails:
  Enabled: true

# RuboCop has no setting to accept how vim aligns parameters.
Layout/AlignParameters:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Assume the programmer knows how bracketed block syntax works
Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/LineLength:
  Max: 92

# Support use of and and or for control flow.
Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%W': ()
    '%w': ()

Style/SignalException:
  EnforcedStyle: only_raise

# Prefer symbols to look like symbols
Style/SymbolArray:
  EnforcedStyle: brackets

Style/RedundantReturn:
  AllowMultipleReturnValues: true

# Not common in Rails projects
Style/Documentation:
  Enabled: false

inherit_from: .rubocop_todo.yml
