require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
  TargetRubyVersion: 2.5
  TargetRailsVersion: 6.0

Rails:
  Enabled: true

Layout/AlignHash:
  EnforcedHashRocketStyle: table

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# Assume the programmer knows how bracketed block syntax works
Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/LineLength:
  Max: 92

# Timestamps are added in migration 007 and we can't change these migrations
# after the fact.
Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/001_create_players.rb'
    - 'db/migrate/002_create_playdates.rb'
    - 'db/migrate/003_create_availabilities.rb'

# Support use of and and or for control flow.
Style/AndOr:
  EnforcedStyle: conditionals

# Disable for strftime/strptime
Style/FormatStringToken:
  Enabled: false

# Prefer maths
Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%W': ()
    '%w': ()

Style/SignalException:
  EnforcedStyle: only_raise

# Prefer symbols to look like symbols
Style/SymbolArray:
  EnforcedStyle: brackets

Style/RedundantReturn:
  AllowMultipleReturnValues: true

# Not common in Rails projects
Style/Documentation:
  Enabled: false

inherit_from: .rubocop_todo.yml
