AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 92

# Support use of and and or for control flow.
Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/SignalException:
  EnforcedStyle: only_raise

Style/RedundantReturn:
  AllowMultipleReturnValues: true

# Not common in Rails projects
Style/Documentation:
  Enabled: false

# RuboCop has no setting to accept how vim aligns parameters.
Style/AlignParameters:
  Enabled: false

inherit_from: .rubocop_todo.yml
