language: ruby

dist: xenial

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

before_script:
  - nvm install 10
  - yarn install

rvm:
  - 2.5
  - 2.6
  - 2.7

branches:
  only:
    - master
